### ISSUE TITLE
Readability: prepending Module name to functions

### ISSUE THREAD

**Issue by Thotht-Ash** [bastixx/ModularBot#2]
It would probably be good to prepend Module Names to functions in an effort to improve readability and debugability.
E.g. `paddle(displayname, message)` would become `Paddle.paddle(displayname, message)`

**Comment by bastixx** [comment]
This is probably a good Idea. It'll also get rid of the ugly 'from X import *' stuff. This was originally there because I was too lazy to keep updating all the imports

**Comment by Thotht-Ash** [comment]
There is a suggestion with `from Modules import *` altho that might require reorganisation of the folder structure

**Comment by bastixx** [comment]
Was fixed in a recent update.
